from django.db import models

# Create your models here.
class AllMeetingsData(models.Model):
    file_date = models.DateField(blank=True, null=True)
    race_number = models.IntegerField(blank=True, null=True)
    tab_number = models.IntegerField(blank=True, null=True)
    horse = models.CharField(max_length=200, blank=True, null=True)
    weight = models.FloatField(blank=True, null=True)
    claim = models.FloatField(blank=True, null=True)
    jockey = models.CharField(max_length=200, blank=True, null=True)
    trainer = models.CharField(max_length=200, blank=True, null=True)
    raceId = models.IntegerField(blank=True, null=True)
    jockeyId = models.IntegerField(blank=True, null=True)
    trainerId = models.IntegerField(blank=True, null=True)
    meeting = models.CharField(max_length=100, blank=True, null=True)
    track_condition = models.CharField(max_length=100, blank=True, null=True)
    barrier = models.IntegerField(blank=True, null=True)
    reliable = models.BooleanField(default=False)
    class_change = models.CharField(max_length=100, blank=True, null=True)
    hist_run_style = models.CharField(max_length=100, blank=True, null=True)
    pred_stlg_pos = models.IntegerField(blank=True, null=True)
    pf_score = models.IntegerField(blank=True, null=True)
    avg_hist_settling_pos = models.FloatField(blank=True, null=True)
    neural_price = models.FloatField(blank=True, null=True)
    neural_rank = models.IntegerField(blank=True, null=True)
    rsfi = models.FloatField(blank=True, null=True)
    last_600m_ranking_late_speed = models.FloatField(blank=True, null=True)
    s_price = models.FloatField(blank=True, null=True)
    tp20p = models.FloatField(blank=True, null=True)
    time_ranking_start_to_finish = models.FloatField(blank=True, null=True)
    wp20p = models.FloatField(blank=True, null=True)
    weight_class_rank = models.IntegerField(blank=True, null=True)
    wptp20p = models.FloatField(blank=True, null=True)
    time_adjust_weight_class_rank = models.IntegerField(blank=True, null=True)
    etr_price = models.FloatField(blank=True, null=True)
    early_time_ranking_to_600m_speed = models.FloatField(blank=True, null=True)
    horseId = models.IntegerField(blank=True, null=True)
    distance = models.FloatField(blank=True, null=True)
    race_class = models.CharField(max_length=100, blank=True, null=True)
    grade = models.CharField(max_length=100, blank=True, null=True)
    horse_age = models.IntegerField(blank=True, null=True)
    horse_sex = models.CharField(max_length=100, blank=True, null=True)
    form_last_10 = models.CharField(max_length=100, blank=True, null=True)
    horse_record = models.CharField(max_length=100, blank=True, null=True)
    record_distance = models.CharField(max_length=100, blank=True, null=True)
    record_track = models.CharField(max_length=100, blank=True, null=True)
    record_track_distance = models.CharField(max_length=100, blank=True, null=True)
    record_firm = models.CharField(max_length=100, blank=True, null=True)
    record_good = models.CharField(max_length=100, blank=True, null=True)
    record_soft = models.CharField(max_length=100, blank=True, null=True)
    record_heavy = models.CharField(max_length=100, blank=True, null=True)
    first_up_record = models.CharField(max_length=100, blank=True, null=True)
    second_up_record = models.CharField(max_length=100, blank=True, null=True)
    form_barrier_1 = models.IntegerField(blank=True, null=True)
    form_class_1 = models.CharField(max_length=100, blank=True, null=True)
    form_distance_1 = models.CharField(max_length=100, blank=True, null=True)
    form_jockey_1 = models.CharField(max_length=100, blank=True, null=True)
    form_margin_1 = models.FloatField(blank=True, null=True)
    form_mtg_date_1 = models.DateField(blank=True, null=True)
    form_other_runners_1 = models.CharField(max_length=100, blank=True, null=True)
    form_pos_1 = models.IntegerField(blank=True, null=True)
    form_price_1 = models.FloatField(blank=True, null=True)
    form_time_1 = models.CharField(max_length=100, blank=True, null=True)
    form_track_1 = models.CharField(max_length=100, blank=True, null=True)
    form_tr_cond_1 = models.CharField(max_length=100, blank=True, null=True)
    form_weight_1 = models.FloatField(blank=True, null=True)
    meeting_id = models.IntegerField(blank=True, null=True)
    race_id = models.IntegerField(blank=True, null=True)
    horse_id = models.IntegerField(blank=True, null=True)
    foal_date = models.DateField(blank=True, null=True)
    sec_time_1 = models.CharField(max_length=100, blank=True, null=True)
    time = models.CharField(max_length=100, blank=True, null=True)
    runner_time = models.FloatField(blank=True, null=True)
    race_starts = models.IntegerField(blank=True, null=True)
    race_wins = models.IntegerField(blank=True, null=True)
    dist_starts = models.IntegerField(blank=True, null=True)
    dist_wins = models.IntegerField(blank=True, null=True)
    track_starts = models.IntegerField(blank=True, null=True)
    track_wins = models.IntegerField(blank=True, null=True)
    tr_dist_starts = models.IntegerField(blank=True, null=True)
    tr_dist_wins = models.IntegerField(blank=True, null=True)
    good_starts = models.IntegerField(blank=True, null=True)
    good_wins = models.IntegerField(blank=True, null=True)
    soft_starts = models.IntegerField(blank=True, null=True)
    soft_wins = models.IntegerField(blank=True, null=True)
    heavy_starts = models.IntegerField(blank=True, null=True)
    heavy_wins = models.IntegerField(blank=True, null=True)
    first_up_starts = models.IntegerField(blank=True, null=True)
    first_up_wins = models.IntegerField(blank=True, null=True)
    second_up_starts = models.IntegerField(blank=True, null=True)
    second_up_wins = models.IntegerField(blank=True, null=True)
    first_up_placings = models.IntegerField(blank=True, null=True)
    second_up_placings = models.IntegerField(blank=True, null=True)
    race_placings = models.IntegerField(blank=True, null=True)
    dist_placings = models.IntegerField(blank=True, null=True)
    track_placings = models.IntegerField(blank=True, null=True)
    tr_dist_placings = models.IntegerField(blank=True, null=True)
    good_placings = models.IntegerField(blank=True, null=True)
    soft_placings = models.IntegerField(blank=True, null=True)
    heavy_placings = models.IntegerField(blank=True, null=True)
    rfs = models.CharField(max_length=100, blank=True, null=True)
    rfs_count = models.IntegerField(blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    last_600m = models.FloatField(blank=True, null=True)
    dist_sr = models.FloatField(blank=True, null=True)
    win_sr = models.FloatField(blank=True, null=True)
    track_sr = models.FloatField(blank=True, null=True)
    tr_dist_sr = models.FloatField(blank=True, null=True)
    good_sr = models.FloatField(blank=True, null=True)
    soft_sr = models.FloatField(blank=True, null=True)
    heavy_sr = models.FloatField(blank=True, null=True)
    first_up_sr = models.FloatField(blank=True, null=True)
    second_up_sr = models.FloatField(blank=True, null=True)
    dlr_1 = models.IntegerField(blank=True, null=True)
    form_barrier_2 = models.IntegerField(blank=True, null=True)
    form_class_2 = models.CharField(max_length=100, blank=True, null=True)
    form_distance_2 = models.CharField(max_length=100, blank=True, null=True)
    form_jockey_2 = models.CharField(max_length=100, blank=True, null=True)
    form_margin_2 = models.FloatField(blank=True, null=True)
    form_mtg_date_2 = models.DateField(blank=True, null=True)
    form_other_runners_2 = models.CharField(max_length=100, blank=True, null=True)
    form_pos_2 = models.IntegerField(blank=True, null=True)
    form_price_2 = models.FloatField(blank=True, null=True)
    form_track_2 = models.CharField(max_length=100, blank=True, null=True)
    form_tr_cond_2 = models.CharField(max_length=100, blank=True, null=True)
    form_weight_2 = models.FloatField(blank=True, null=True)
    form_time_2 = models.CharField(max_length=100, blank=True, null=True)
    sec_time_2 = models.CharField(max_length=100, blank=True, null=True)
    dlr_2 = models.IntegerField(blank=True, null=True)
    form_barrier_3 = models.IntegerField(blank=True, null=True)
    form_class_3 = models.CharField(max_length=100, blank=True, null=True)
    form_distance_3 = models.CharField(max_length=100, blank=True, null=True)
    form_jockey_3 = models.CharField(max_length=100, blank=True, null=True)
    form_margin_3 = models.FloatField(blank=True, null=True)
    form_mtg_date_3 = models.DateField(blank=True, null=True)
    form_other_runners_3 = models.CharField(max_length=100, blank=True, null=True)
    form_pos_3 = models.IntegerField(blank=True, null=True)
    form_price_3 = models.FloatField(blank=True, null=True)
    form_track_3 = models.CharField(max_length=100, blank=True, null=True)
    form_tr_cond_3 = models.CharField(max_length=100, blank=True, null=True)
    form_weight_3 = models.FloatField(blank=True, null=True)
    form_time_3 = models.CharField(max_length=100, blank=True, null=True)
    sec_time_3 = models.CharField(max_length=100, blank=True, null=True)
    dlr_3 = models.IntegerField(blank=True, null=True)
    seconds = models.FloatField(blank=True, null=True)
    msecs = models.FloatField(blank=True, null=True)
    time1 = models.FloatField(blank=True, null=True)
    wght_chg = models.FloatField(blank=True, null=True)
    dist_chg = models.FloatField(blank=True, null=True)
    bar_chg = models.FloatField(blank=True, null=True)
    wght_over_limit = models.FloatField(blank=True, null=True)
    ave_spd = models.FloatField(blank=True, null=True)
    dbr_1_2 = models.IntegerField(blank=True, null=True)
    dbr_2_3 = models.IntegerField(blank=True, null=True)
    bf_rtd_price = models.FloatField(blank=True, null=True)
    mktrk = models.IntegerField(blank=True, null=True)
    starters = models.IntegerField(blank=True, null=True)
    def __str__(self):
        return self.horse
    
class FormAllMeetingsData(models.Model):
    file_date = models.DateField(blank=True, null=True)
    meeting_date = models.CharField(max_length=100, blank=True, null=True)
    track = models.CharField(max_length=100, blank=True, null=True)
    race_number = models.IntegerField(blank=True, null=True)
    start_time = models.CharField(max_length=100, blank=True, null=True)
    distance = models.FloatField(blank=True, null=True)
    age_restrictions = models.CharField(max_length=100, blank=True, null=True)
    class_restrictions = models.CharField(max_length=100, blank=True, null=True)
    weight_restrictions = models.FloatField(blank=True, null=True)
    race_prizemoney = models.CharField(max_length=100, blank=True, null=True)
    sex_restrictions = models.CharField(max_length=100, blank=True, null=True)
    weight_type = models.CharField(max_length=100, blank=True, null=True)
    race_name = models.CharField(max_length=100, blank=True, null=True)
    jockeys_can_claim = models.CharField(max_length=100, blank=True, null=True)
    grade = models.CharField(max_length=100, blank=True, null=True)
    horse_name = models.CharField(max_length=100, blank=True, null=True)
    horse_age = models.IntegerField(blank=True, null=True)
    horse_sex = models.CharField(max_length=100, blank=True, null=True)
    horse_sire = models.CharField(max_length=100, blank=True, null=True)
    horse_dam = models.CharField(max_length=100, blank=True, null=True)
    horse_number = models.IntegerField(blank=True, null=True)
    horse_jockey = models.CharField(max_length=100, blank=True, null=True)
    horse_barrier = models.IntegerField(blank=True, null=True)
    horse_trainer = models.CharField(max_length=100, blank=True, null=True)
    horse_weight = models.FloatField(blank=True, null=True)
    horse_claim = models.FloatField(blank=True, null=True)
    horse_last10 = models.CharField(max_length=100, blank=True, null=True)
    horse_record = models.CharField(max_length=100, blank=True, null=True)
    horse_record_distance = models.CharField(max_length=100, blank=True, null=True)
    horse_record_track = models.CharField(max_length=100, blank=True, null=True)
    horse_record_track_distance = models.CharField(max_length=100, blank=True, null=True)
    horse_record_firm = models.CharField(max_length=100, blank=True, null=True)
    horse_record_good = models.CharField(max_length=100, blank=True, null=True)
    horse_record_soft = models.CharField(max_length=100, blank=True, null=True)
    horse_record_heavy = models.CharField(max_length=100, blank=True, null=True)
    horse_record_jumps = models.CharField(max_length=100, blank=True, null=True)
    horse_record_firs_up = models.CharField(max_length=100, blank=True, null=True)
    horse_record_second_up = models.CharField(max_length=100, blank=True, null=True)
    horse_price_money = models.FloatField(blank=True, null=True)
    form_barrier = models.IntegerField(blank=True, null=True)
    form_class = models.CharField(max_length=100, blank=True, null=True)
    form_distance = models.FloatField(blank=True, null=True)
    form_jockey = models.CharField(max_length=100, blank=True, null=True)
    form_margin = models.FloatField(blank=True, null=True)
    form_meeting_date = models.DateField(blank=True, null=True)
    form_name = models.CharField(max_length=100, blank=True, null=True)
    form_other_runners = models.CharField(max_length=100, blank=True, null=True)
    form_position = models.IntegerField(blank=True, null=True)
    form_price = models.FloatField(blank=True, null=True)
    form_time = models.CharField(max_length=100, blank=True, null=True)
    form_track = models.CharField(max_length=100, blank=True, null=True)
    form_track_condition = models.CharField(max_length=100, blank=True, null=True)
    form_weight = models.FloatField(blank=True, null=True)
    horse_record_synthetic = models.CharField(max_length=100, blank=True, null=True)
    meeting_id = models.IntegerField(blank=True, null=True)
    race_id = models.IntegerField(blank=True, null=True)
    horse_id = models.IntegerField(blank=True, null=True)
    horse_trainer_id = models.IntegerField(blank=True, null=True)
    horse_jockey_id = models.IntegerField(blank=True, null=True)
    form_trainer_id = models.IntegerField(blank=True, null=True)
    form_jockey_id = models.IntegerField(blank=True, null=True)
    foal_date = models.DateField(blank=True, null=True)
    pricemoney = models.FloatField(blank=True, null=True)
    sectional = models.CharField(max_length=100, blank=True, null=True)
    pricemoney_won = models.FloatField(blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)

class MeetingRating(models.Model):
    file_date = models.DateField(blank=True, null=True)
    meeting = models.CharField(max_length=100, blank=True, null=True)
    track_condition = models.CharField(max_length=100, blank=True, null=True)
    time = models.CharField(max_length=100, blank=True, null=True)
    race_number = models.IntegerField(blank=True, null=True)
    race_class = models.CharField(max_length=100, blank=True, null=True)
    class_change = models.FloatField(blank=True, null=True)
    distance = models.FloatField(blank=True, null=True)
    distance_change = models.FloatField(blank=True, null=True)
    form_last_10 = models.CharField(max_length=100, blank=True, null=True)
    tab_no = models.IntegerField(blank=True, null=True)
    horse = models.CharField(max_length=100, blank=True, null=True)
    barrier = models.IntegerField(blank=True, null=True)
    barrier_change = models.FloatField(blank=True, null=True)
    prediction = models.FloatField(blank=True, null=True)
    rating = models.FloatField(blank=True, null=True)
    jky = models.FloatField(blank=True, null=True)
    trn = models.FloatField(blank=True, null=True)
    rank_class = models.IntegerField(blank=True, null=True)
    rank_lsf_pos = models.FloatField(blank=True, null=True)
    rank_lsf_pos_2 = models.FloatField(blank=True, null=True)
    rank_dist_chg = models.FloatField(blank=True, null=True)
    rank_dlr = models.FloatField(blank=True, null=True)
    rank_mkt_rk = models.FloatField(blank=True, null=True)
    rank_rfs = models.FloatField(blank=True, null=True)
    rank_pfscore = models.FloatField(blank=True, null=True)
    rank_stlg_pos = models.FloatField(blank=True, null=True)
    rank_barrier = models.FloatField(blank=True, null=True)
    rank_weight = models.FloatField(blank=True, null=True)
    jockey = models.CharField(max_length=100, blank=True, null=True)
    jockey_a2e = models.FloatField(blank=True, null=True)
    weight = models.FloatField(blank=True, null=True)
    weight_change = models.FloatField(blank=True, null=True)
    price_sp = models.FloatField(blank=True, null=True)
    hist_run_style = models.CharField(max_length=100, blank=True, null=True)
    pred_stlg_pos = models.FloatField(blank=True, null=True)
    trainer = models.CharField(max_length=100, blank=True, null=True)
    trainer_a2e = models.FloatField(blank=True, null=True)
    mkt_rk = models.FloatField(blank=True, null=True)
    dlr_1 = models.FloatField(blank=True, null=True)
    form_margin_1 = models.FloatField(blank=True, null=True)
    form_dist_1 = models.FloatField(blank=True, null=True)
    runner_time = models.FloatField(blank=True, null=True)
    last_600m = models.FloatField(blank=True, null=True)
    ave_spd_mts_sec = models.FloatField(blank=True, null=True)
    form_jky_1 = models.CharField(max_length=100, blank=True, null=True)
    form_weight_1 = models.FloatField(blank=True, null=True)
    form_barrier_1 = models.IntegerField(blank=True, null=True)
    form_tr_cond_1 = models.CharField(max_length=100, blank=True, null=True)
    form_cl_1 = models.CharField(max_length=100, blank=True, null=True)
    form_other_runners_1 = models.CharField(max_length=100, blank=True, null=True)
    form_margin_2 = models.FloatField(blank=True, null=True)
    form_dist_2 = models.FloatField(blank=True, null=True)
    form_time_2 = models.CharField(max_length=100, blank=True, null=True)
    sec_time_2 = models.CharField(max_length=100, blank=True, null=True)
    form_jky_2 = models.CharField(max_length=100, blank=True, null=True)
    form_weight_2 = models.FloatField(blank=True, null=True)
    form_barrier_2 = models.IntegerField(blank=True, null=True)
    form_tr_cond_2 = models.CharField(max_length=100, blank=True, null=True)
    form_class_2 = models.CharField(max_length=100, blank=True, null=True)
    form_other_runners_2 = models.CharField(max_length=100, blank=True, null=True)
    starts = models.IntegerField(blank=True, null=True)
    w_sr = models.FloatField(blank=True, null=True)
    dist_st = models.FloatField(blank=True, null=True)
    dist_sr = models.FloatField(blank=True, null=True)
    tr_st = models.FloatField(blank=True, null=True)
    tr_sr = models.FloatField(blank=True, null=True)
    g_st = models.FloatField(blank=True, null=True)
    g_w = models.FloatField(blank=True, null=True)
    g_sr = models.FloatField(blank=True, null=True)
    s_st = models.FloatField(blank=True, null=True)
    s_w = models.FloatField(blank=True, null=True)
    s_sr = models.FloatField(blank=True, null=True)
    h_st = models.FloatField(blank=True, null=True)
    h_w = models.FloatField(blank=True, null=True)
    h_sr = models.FloatField(blank=True, null=True)
    starters = models.IntegerField(blank=True, null=True)

